export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const TOGGLE_EDIT_TODO = 'TOGGLE_EDIT_TODO';
export const TOGGLE_STAR_TODO = 'TOGGLE_STAR_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';